// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZ2FiaUy0NcXSPR669Q9Cg71EZ5m_wFE',
    appId: '1:221292665960:web:5071a920e7849e3f742fdd',
    messagingSenderId: '221292665960',
    projectId: 'otakulink-1d1d8',
    authDomain: 'otakulink-1d1d8.firebaseapp.com',
    storageBucket: 'otakulink-1d1d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxykTo-7i4q9OC-kWYj82mPHhC84Nbfko',
    appId: '1:221292665960:android:2311e9ebf206190e742fdd',
    messagingSenderId: '221292665960',
    projectId: 'otakulink-1d1d8',
    storageBucket: 'otakulink-1d1d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyv2x-aAszLYIl4f4vny5YhBF5camNzf4',
    appId: '1:221292665960:ios:3ab4ce528f12a5c0742fdd',
    messagingSenderId: '221292665960',
    projectId: 'otakulink-1d1d8',
    storageBucket: 'otakulink-1d1d8.firebasestorage.app',
    iosClientId: '221292665960-jpn90l2dmjf3r6s9fmdi1bna9rtphkng.apps.googleusercontent.com',
    iosBundleId: 'com.example.otakulink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyv2x-aAszLYIl4f4vny5YhBF5camNzf4',
    appId: '1:221292665960:ios:3ab4ce528f12a5c0742fdd',
    messagingSenderId: '221292665960',
    projectId: 'otakulink-1d1d8',
    storageBucket: 'otakulink-1d1d8.firebasestorage.app',
    iosClientId: '221292665960-jpn90l2dmjf3r6s9fmdi1bna9rtphkng.apps.googleusercontent.com',
    iosBundleId: 'com.example.otakulink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADZ2FiaUy0NcXSPR669Q9Cg71EZ5m_wFE',
    appId: '1:221292665960:web:3195d35b558de4e7742fdd',
    messagingSenderId: '221292665960',
    projectId: 'otakulink-1d1d8',
    authDomain: 'otakulink-1d1d8.firebaseapp.com',
    storageBucket: 'otakulink-1d1d8.firebasestorage.app',
  );
}
